/* key-model.c generated by valac 0.20.1.19-a6516, the Vala compiler
 * generated from key-model.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gdk/gdk.h>
#include <gee.h>


#define CARIBOU_TYPE_ISCANNABLE_ITEM (caribou_iscannable_item_get_type ())
#define CARIBOU_ISCANNABLE_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CARIBOU_TYPE_ISCANNABLE_ITEM, CaribouIScannableItem))
#define CARIBOU_IS_ISCANNABLE_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CARIBOU_TYPE_ISCANNABLE_ITEM))
#define CARIBOU_ISCANNABLE_ITEM_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), CARIBOU_TYPE_ISCANNABLE_ITEM, CaribouIScannableItemIface))

typedef struct _CaribouIScannableItem CaribouIScannableItem;
typedef struct _CaribouIScannableItemIface CaribouIScannableItemIface;

#define CARIBOU_TYPE_IKEYBOARD_OBJECT (caribou_ikeyboard_object_get_type ())
#define CARIBOU_IKEYBOARD_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CARIBOU_TYPE_IKEYBOARD_OBJECT, CaribouIKeyboardObject))
#define CARIBOU_IS_IKEYBOARD_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CARIBOU_TYPE_IKEYBOARD_OBJECT))
#define CARIBOU_IKEYBOARD_OBJECT_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), CARIBOU_TYPE_IKEYBOARD_OBJECT, CaribouIKeyboardObjectIface))

typedef struct _CaribouIKeyboardObject CaribouIKeyboardObject;
typedef struct _CaribouIKeyboardObjectIface CaribouIKeyboardObjectIface;

#define CARIBOU_TYPE_KEY_MODEL (caribou_key_model_get_type ())
#define CARIBOU_KEY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CARIBOU_TYPE_KEY_MODEL, CaribouKeyModel))
#define CARIBOU_KEY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CARIBOU_TYPE_KEY_MODEL, CaribouKeyModelClass))
#define CARIBOU_IS_KEY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CARIBOU_TYPE_KEY_MODEL))
#define CARIBOU_IS_KEY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CARIBOU_TYPE_KEY_MODEL))
#define CARIBOU_KEY_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CARIBOU_TYPE_KEY_MODEL, CaribouKeyModelClass))

typedef struct _CaribouKeyModel CaribouKeyModel;
typedef struct _CaribouKeyModelClass CaribouKeyModelClass;
typedef struct _CaribouKeyModelPrivate CaribouKeyModelPrivate;

#define CARIBOU_TYPE_MODIFIER_STATE (caribou_modifier_state_get_type ())

#define CARIBOU_TYPE_XADAPTER (caribou_xadapter_get_type ())
#define CARIBOU_XADAPTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CARIBOU_TYPE_XADAPTER, CaribouXAdapter))
#define CARIBOU_XADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CARIBOU_TYPE_XADAPTER, CaribouXAdapterClass))
#define CARIBOU_IS_XADAPTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CARIBOU_TYPE_XADAPTER))
#define CARIBOU_IS_XADAPTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CARIBOU_TYPE_XADAPTER))
#define CARIBOU_XADAPTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CARIBOU_TYPE_XADAPTER, CaribouXAdapterClass))

typedef struct _CaribouXAdapter CaribouXAdapter;
typedef struct _CaribouXAdapterClass CaribouXAdapterClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define CARIBOU_TYPE_MODIFIER_MAP_ENTRY (caribou_modifier_map_entry_get_type ())
typedef struct _CaribouModifierMapEntry CaribouModifierMapEntry;

#define CARIBOU_TYPE_LABEL_MAP_ENTRY (caribou_label_map_entry_get_type ())
typedef struct _CaribouLabelMapEntry CaribouLabelMapEntry;

struct _CaribouIScannableItemIface {
	GTypeInterface parent_iface;
	gboolean (*get_scan_stepping) (CaribouIScannableItem* self);
	void (*set_scan_stepping) (CaribouIScannableItem* self, gboolean value);
	gboolean (*get_scan_selected) (CaribouIScannableItem* self);
	void (*set_scan_selected) (CaribouIScannableItem* self, gboolean value);
};

struct _CaribouIKeyboardObjectIface {
	GTypeInterface parent_iface;
	CaribouIKeyboardObject** (*get_children) (CaribouIKeyboardObject* self, int* result_length1);
	CaribouKeyModel** (*get_keys) (CaribouIKeyboardObject* self, int* result_length1);
};

typedef enum  {
	CARIBOU_MODIFIER_STATE_NONE,
	CARIBOU_MODIFIER_STATE_LATCHED,
	CARIBOU_MODIFIER_STATE_LOCKED
} CaribouModifierState;

struct _CaribouKeyModel {
	GObject parent_instance;
	CaribouKeyModelPrivate * priv;
	CaribouModifierState modifier_state;
};

struct _CaribouKeyModelClass {
	GObjectClass parent_class;
};

struct _CaribouKeyModelPrivate {
	gchar* _align;
	gdouble _width;
	gchar* _toggle;
	gboolean _repeatable;
	GdkModifierType mod_mask;
	gboolean _show_subkeys;
	gchar* _name;
	guint _keyval;
	gchar* _text;
	guint* _keyvals;
	gint _keyvals_length1;
	gint __keyvals_size_;
	gchar* _label;
	gboolean _scan_stepping;
	gboolean _scan_selected;
	guint hold_tid;
	CaribouXAdapter* xadapter;
	GeeArrayList* extended_keys;
};

struct _CaribouModifierMapEntry {
	gchar* name;
	GdkModifierType mask;
};

struct _CaribouLabelMapEntry {
	gchar* name;
	gchar* label;
};


static gpointer caribou_key_model_parent_class = NULL;
static CaribouIScannableItemIface* caribou_key_model_caribou_iscannable_item_parent_iface = NULL;
static CaribouIKeyboardObjectIface* caribou_key_model_caribou_ikeyboard_object_parent_iface = NULL;

GType caribou_iscannable_item_get_type (void) G_GNUC_CONST;
GType caribou_key_model_get_type (void) G_GNUC_CONST;
GType caribou_ikeyboard_object_get_type (void) G_GNUC_CONST;
GType caribou_modifier_state_get_type (void) G_GNUC_CONST;
GType caribou_xadapter_get_type (void) G_GNUC_CONST;
#define CARIBOU_KEY_MODEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CARIBOU_TYPE_KEY_MODEL, CaribouKeyModelPrivate))
enum  {
	CARIBOU_KEY_MODEL_DUMMY_PROPERTY,
	CARIBOU_KEY_MODEL_ALIGN,
	CARIBOU_KEY_MODEL_WIDTH,
	CARIBOU_KEY_MODEL_TOGGLE,
	CARIBOU_KEY_MODEL_REPEATABLE,
	CARIBOU_KEY_MODEL_IS_MODIFIER,
	CARIBOU_KEY_MODEL_SHOW_SUBKEYS,
	CARIBOU_KEY_MODEL_NAME,
	CARIBOU_KEY_MODEL_KEYVAL,
	CARIBOU_KEY_MODEL_TEXT,
	CARIBOU_KEY_MODEL_LABEL,
	CARIBOU_KEY_MODEL_SCAN_STEPPING,
	CARIBOU_KEY_MODEL_SCAN_SELECTED
};
GType caribou_modifier_map_entry_get_type (void) G_GNUC_CONST;
CaribouModifierMapEntry* caribou_modifier_map_entry_dup (const CaribouModifierMapEntry* self);
void caribou_modifier_map_entry_free (CaribouModifierMapEntry* self);
void caribou_modifier_map_entry_copy (const CaribouModifierMapEntry* self, CaribouModifierMapEntry* dest);
void caribou_modifier_map_entry_destroy (CaribouModifierMapEntry* self);
GType caribou_label_map_entry_get_type (void) G_GNUC_CONST;
CaribouLabelMapEntry* caribou_label_map_entry_dup (const CaribouLabelMapEntry* self);
void caribou_label_map_entry_free (CaribouLabelMapEntry* self);
void caribou_label_map_entry_copy (const CaribouLabelMapEntry* self, CaribouLabelMapEntry* dest);
void caribou_label_map_entry_destroy (CaribouLabelMapEntry* self);
CaribouKeyModel* caribou_key_model_new (const gchar* name, const gchar* text);
CaribouKeyModel* caribou_key_model_construct (GType object_type, const gchar* name, const gchar* text);
static void caribou_key_model_set_name (CaribouKeyModel* self, const gchar* value);
static void caribou_key_model_set_text (CaribouKeyModel* self, const gchar* value);
static void _vala_array_add3 (guint** array, int* length, int* size, guint value);
static void _vala_array_add4 (guint** array, int* length, int* size, guint value);
static void caribou_key_model_set_keyval (CaribouKeyModel* self, guint value);
static void caribou_key_model_set_label (CaribouKeyModel* self, const gchar* value);
CaribouXAdapter* caribou_xadapter_get_default (void);
void caribou_key_model_add_subkey (CaribouKeyModel* self, CaribouKeyModel* key);
static void caribou_key_model_on_subkey_released (CaribouKeyModel* self, CaribouKeyModel* key);
static void _caribou_key_model_on_subkey_released_caribou_ikeyboard_object_key_released (CaribouIKeyboardObject* _sender, CaribouKeyModel* key, gpointer self);
static void caribou_key_model_set_show_subkeys (CaribouKeyModel* self, gboolean value);
void caribou_key_model_press (CaribouKeyModel* self);
gboolean caribou_key_model_get_is_modifier (CaribouKeyModel* self);
void caribou_xadapter_mod_lock (CaribouXAdapter* self, guint mask);
gboolean caribou_key_model_get_repeatable (CaribouKeyModel* self);
void caribou_xadapter_keyval_press (CaribouXAdapter* self, guint keyval);
guint caribou_key_model_get_keyval (CaribouKeyModel* self);
static gboolean caribou_key_model_on_key_held (CaribouKeyModel* self);
static gboolean _caribou_key_model_on_key_held_gsource_func (gpointer self);
void caribou_key_model_release (CaribouKeyModel* self);
void caribou_xadapter_mod_unlock (CaribouXAdapter* self, guint mask);
void caribou_xadapter_keyval_release (CaribouXAdapter* self, guint keyval);
CaribouKeyModel** caribou_key_model_get_extended_keys (CaribouKeyModel* self, int* result_length1);
static CaribouKeyModel** caribou_key_model_real_get_keys (CaribouIKeyboardObject* base, int* result_length1);
static CaribouIKeyboardObject** caribou_key_model_real_get_children (CaribouIKeyboardObject* base, int* result_length1);
void caribou_key_model_activate (CaribouKeyModel* self);
static gboolean __lambda2_ (CaribouKeyModel* self);
static gboolean ___lambda2__gsource_func (gpointer self);
const gchar* caribou_key_model_get_align (CaribouKeyModel* self);
void caribou_key_model_set_align (CaribouKeyModel* self, const gchar* value);
gdouble caribou_key_model_get_width (CaribouKeyModel* self);
void caribou_key_model_set_width (CaribouKeyModel* self, gdouble value);
const gchar* caribou_key_model_get_toggle (CaribouKeyModel* self);
void caribou_key_model_set_toggle (CaribouKeyModel* self, const gchar* value);
void caribou_key_model_set_repeatable (CaribouKeyModel* self, gboolean value);
void caribou_key_model_set_is_modifier (CaribouKeyModel* self, gboolean value);
gboolean caribou_key_model_get_show_subkeys (CaribouKeyModel* self);
const gchar* caribou_key_model_get_name (CaribouKeyModel* self);
const gchar* caribou_key_model_get_text (CaribouKeyModel* self);
const gchar* caribou_key_model_get_label (CaribouKeyModel* self);
static void caribou_key_model_finalize (GObject* obj);
gboolean caribou_iscannable_item_get_scan_stepping (CaribouIScannableItem* self);
gboolean caribou_iscannable_item_get_scan_selected (CaribouIScannableItem* self);
static void _vala_caribou_key_model_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
void caribou_iscannable_item_set_scan_stepping (CaribouIScannableItem* self, gboolean value);
void caribou_iscannable_item_set_scan_selected (CaribouIScannableItem* self, gboolean value);
static void _vala_caribou_key_model_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);

static const CaribouModifierMapEntry CARIBOU_KEY_MODEL_mod_map[3] = {{"Control_L", GDK_CONTROL_MASK}, {"Alt_L", GDK_MOD1_MASK}, {NULL, 0}};
static const CaribouLabelMapEntry CARIBOU_KEY_MODEL_label_map[16] = {{"BackSpace", "\xe2\x8c\xab"}, {"space", " "}, {"Return", "\xe2\x8f\x8e"}, {"Return", "\xe2\x8f\x8e"}, {"Control_L", "Ctrl"}, {"Control_R", "Ctrl"}, {"Alt_L", "Alt"}, {"Alt_R", "Alt"}, {"Caribou_Prefs", "\xe2\x8c\xa8"}, {"Caribou_ShiftUp", "\xe2\xac\x86"}, {"Caribou_ShiftDown", "\xe2\xac\x87"}, {"Caribou_Emoticons", "\xe2\x98\xba"}, {"Caribou_Symbols", "123"}, {"Caribou_Symbols_More", "{#*"}, {"Caribou_Alpha", "Abc"}, {"Caribou_Repeat", "\xe2\x99\xbb"}};

static gboolean string_get_next_char (const gchar* self, gint* index, gunichar* c) {
	gunichar _vala_c = 0U;
	gboolean result = FALSE;
	gint _tmp0_;
	gunichar _tmp1_ = 0U;
	gunichar _tmp2_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = *index;
	_tmp1_ = g_utf8_get_char (((gchar*) self) + _tmp0_);
	_vala_c = _tmp1_;
	_tmp2_ = _vala_c;
	if (_tmp2_ != ((gunichar) 0)) {
		gint _tmp3_;
		gchar* _tmp4_ = NULL;
		_tmp3_ = *index;
		_tmp4_ = g_utf8_next_char (((gchar*) self) + _tmp3_);
		*index = (gint) (_tmp4_ - ((gchar*) self));
		result = TRUE;
		if (c) {
			*c = _vala_c;
		}
		return result;
	} else {
		result = FALSE;
		if (c) {
			*c = _vala_c;
		}
		return result;
	}
	if (c) {
		*c = _vala_c;
	}
}


static void _vala_array_add3 (guint** array, int* length, int* size, guint value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (guint, *array, *size);
	}
	(*array)[(*length)++] = value;
}


static void _vala_array_add4 (guint** array, int* length, int* size, guint value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (guint, *array, *size);
	}
	(*array)[(*length)++] = value;
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	glong string_length = 0L;
	gint _tmp0_;
	gint _tmp1_;
	glong _tmp2_;
	glong _tmp5_;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_;
	gboolean _tmp12_;
	gboolean _tmp13_ = FALSE;
	glong _tmp14_;
	gboolean _tmp17_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	glong _tmp22_;
	gchar* _tmp23_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	_tmp2_ = start;
	if (_tmp2_ < ((glong) 0)) {
		glong _tmp3_;
		glong _tmp4_;
		_tmp3_ = string_length;
		_tmp4_ = start;
		start = _tmp3_ + _tmp4_;
	}
	_tmp5_ = end;
	if (_tmp5_ < ((glong) 0)) {
		glong _tmp6_;
		glong _tmp7_;
		_tmp6_ = string_length;
		_tmp7_ = end;
		end = _tmp6_ + _tmp7_;
	}
	_tmp9_ = start;
	if (_tmp9_ >= ((glong) 0)) {
		glong _tmp10_;
		glong _tmp11_;
		_tmp10_ = start;
		_tmp11_ = string_length;
		_tmp8_ = _tmp10_ <= _tmp11_;
	} else {
		_tmp8_ = FALSE;
	}
	_tmp12_ = _tmp8_;
	g_return_val_if_fail (_tmp12_, NULL);
	_tmp14_ = end;
	if (_tmp14_ >= ((glong) 0)) {
		glong _tmp15_;
		glong _tmp16_;
		_tmp15_ = end;
		_tmp16_ = string_length;
		_tmp13_ = _tmp15_ <= _tmp16_;
	} else {
		_tmp13_ = FALSE;
	}
	_tmp17_ = _tmp13_;
	g_return_val_if_fail (_tmp17_, NULL);
	_tmp18_ = start;
	_tmp19_ = end;
	g_return_val_if_fail (_tmp18_ <= _tmp19_, NULL);
	_tmp20_ = start;
	_tmp21_ = end;
	_tmp22_ = start;
	_tmp23_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) (_tmp21_ - _tmp22_));
	result = _tmp23_;
	return result;
}


static gchar* g_unichar_to_string (gunichar self) {
	gchar* result = NULL;
	gchar* str = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_;
	_tmp0_ = g_new0 (gchar, 7);
	str = (gchar*) _tmp0_;
	_tmp1_ = str;
	g_unichar_to_utf8 (self, _tmp1_);
	result = str;
	return result;
}


CaribouKeyModel* caribou_key_model_construct (GType object_type, const gchar* name, const gchar* text) {
	CaribouKeyModel * self = NULL;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gint i = 0;
	GdkModifierType _tmp18_;
	gint _tmp49_;
	CaribouXAdapter* _tmp74_ = NULL;
	GeeArrayList* _tmp75_;
	g_return_val_if_fail (name != NULL, NULL);
	self = (CaribouKeyModel*) g_object_new (object_type, NULL);
	_tmp0_ = name;
	caribou_key_model_set_name (self, _tmp0_);
	_tmp1_ = text;
	caribou_key_model_set_text (self, _tmp1_);
	self->priv->mod_mask = (GdkModifierType) 0;
	i = 0;
	{
		CaribouModifierMapEntry entry = {0};
		gint _tmp2_;
		CaribouModifierMapEntry _tmp3_;
		CaribouModifierMapEntry _tmp4_ = {0};
		_tmp2_ = i;
		_tmp3_ = CARIBOU_KEY_MODEL_mod_map[_tmp2_];
		caribou_modifier_map_entry_copy (&_tmp3_, &_tmp4_);
		entry = _tmp4_;
		{
			gboolean _tmp5_ = FALSE;
			_tmp5_ = TRUE;
			while (TRUE) {
				gboolean _tmp6_;
				CaribouModifierMapEntry _tmp11_;
				const gchar* _tmp12_;
				const gchar* _tmp13_;
				CaribouModifierMapEntry _tmp14_;
				const gchar* _tmp15_;
				_tmp6_ = _tmp5_;
				if (!_tmp6_) {
					gint _tmp7_;
					gint _tmp8_;
					CaribouModifierMapEntry _tmp9_;
					CaribouModifierMapEntry _tmp10_ = {0};
					_tmp7_ = i;
					i = _tmp7_ + 1;
					_tmp8_ = i;
					_tmp9_ = CARIBOU_KEY_MODEL_mod_map[_tmp8_];
					caribou_modifier_map_entry_copy (&_tmp9_, &_tmp10_);
					caribou_modifier_map_entry_destroy (&entry);
					entry = _tmp10_;
				}
				_tmp5_ = FALSE;
				_tmp11_ = entry;
				_tmp12_ = _tmp11_.name;
				if (!(_tmp12_ != NULL)) {
					break;
				}
				_tmp13_ = name;
				_tmp14_ = entry;
				_tmp15_ = _tmp14_.name;
				if (g_strcmp0 (_tmp13_, _tmp15_) == 0) {
					CaribouModifierMapEntry _tmp16_;
					GdkModifierType _tmp17_;
					_tmp16_ = entry;
					_tmp17_ = _tmp16_.mask;
					self->priv->mod_mask = _tmp17_;
				}
			}
		}
		caribou_modifier_map_entry_destroy (&entry);
	}
	_tmp18_ = self->priv->mod_mask;
	if (_tmp18_ == 0) {
		const gchar* _tmp19_;
		_tmp19_ = text;
		if (_tmp19_ != NULL) {
			gint index = 0;
			gunichar uc = 0U;
			index = 0;
			while (TRUE) {
				const gchar* _tmp20_;
				gunichar _tmp21_ = 0U;
				gboolean _tmp22_ = FALSE;
				guint keyval = 0U;
				gunichar _tmp23_;
				guint _tmp24_ = 0U;
				guint _tmp25_;
				gunichar _tmp26_;
				_tmp20_ = text;
				_tmp22_ = string_get_next_char (_tmp20_, &index, &_tmp21_);
				uc = _tmp21_;
				if (!_tmp22_) {
					break;
				}
				_tmp23_ = uc;
				_tmp24_ = gdk_unicode_to_keyval ((guint32) _tmp23_);
				keyval = _tmp24_;
				_tmp25_ = keyval;
				_tmp26_ = uc;
				if ((_tmp25_ != ((guint) _tmp26_)) | 0x01000000) {
					guint* _tmp27_;
					gint _tmp27__length1;
					guint _tmp28_;
					_tmp27_ = self->priv->_keyvals;
					_tmp27__length1 = self->priv->_keyvals_length1;
					_tmp28_ = keyval;
					_vala_array_add3 (&self->priv->_keyvals, &self->priv->_keyvals_length1, &self->priv->__keyvals_size_, _tmp28_);
				}
			}
		} else {
			guint keyval = 0U;
			const gchar* _tmp29_;
			guint _tmp30_ = 0U;
			gboolean _tmp31_ = FALSE;
			guint _tmp32_;
			gboolean _tmp34_;
			guint _tmp37_;
			_tmp29_ = name;
			_tmp30_ = gdk_keyval_from_name (_tmp29_);
			keyval = _tmp30_;
			_tmp32_ = keyval;
			if (_tmp32_ != ((guint) GDK_KEY_VoidSymbol)) {
				guint _tmp33_;
				_tmp33_ = keyval;
				_tmp31_ = _tmp33_ != ((guint) 0);
			} else {
				_tmp31_ = FALSE;
			}
			_tmp34_ = _tmp31_;
			if (_tmp34_) {
				guint* _tmp35_;
				gint _tmp35__length1;
				guint _tmp36_;
				_tmp35_ = self->priv->_keyvals;
				_tmp35__length1 = self->priv->_keyvals_length1;
				_tmp36_ = keyval;
				_vala_array_add4 (&self->priv->_keyvals, &self->priv->_keyvals_length1, &self->priv->__keyvals_size_, _tmp36_);
			}
			_tmp37_ = keyval;
			caribou_key_model_set_keyval (self, _tmp37_);
		}
	}
	{
		gboolean _tmp38_ = FALSE;
		i = 0;
		_tmp38_ = TRUE;
		while (TRUE) {
			gboolean _tmp39_;
			gint _tmp41_;
			gint _tmp42_;
			CaribouLabelMapEntry _tmp43_;
			const gchar* _tmp44_;
			const gchar* _tmp45_;
			_tmp39_ = _tmp38_;
			if (!_tmp39_) {
				gint _tmp40_;
				_tmp40_ = i;
				i = _tmp40_ + 1;
			}
			_tmp38_ = FALSE;
			_tmp41_ = i;
			if (!(_tmp41_ < G_N_ELEMENTS (CARIBOU_KEY_MODEL_label_map))) {
				break;
			}
			_tmp42_ = i;
			_tmp43_ = CARIBOU_KEY_MODEL_label_map[_tmp42_];
			_tmp44_ = _tmp43_.name;
			_tmp45_ = name;
			if (g_strcmp0 (_tmp44_, _tmp45_) == 0) {
				gint _tmp46_;
				CaribouLabelMapEntry _tmp47_;
				const gchar* _tmp48_;
				_tmp46_ = i;
				_tmp47_ = CARIBOU_KEY_MODEL_label_map[_tmp46_];
				_tmp48_ = _tmp47_.label;
				caribou_key_model_set_label (self, _tmp48_);
				break;
			}
		}
	}
	_tmp49_ = i;
	if (_tmp49_ == G_N_ELEMENTS (CARIBOU_KEY_MODEL_label_map)) {
		const gchar* _tmp50_;
		_tmp50_ = text;
		if (_tmp50_ != NULL) {
			const gchar* _tmp51_;
			_tmp51_ = text;
			caribou_key_model_set_label (self, _tmp51_);
		} else {
			const gchar* _tmp52_;
			gboolean _tmp53_ = FALSE;
			_tmp52_ = name;
			_tmp53_ = g_str_has_prefix (_tmp52_, "Caribou_");
			if (_tmp53_) {
				const gchar* _tmp54_;
				gint _tmp55_;
				gint _tmp56_;
				const gchar* _tmp57_;
				gint _tmp58_;
				gint _tmp59_;
				gchar* _tmp60_ = NULL;
				gchar* _tmp61_;
				_tmp54_ = name;
				_tmp55_ = strlen ("Caribou_");
				_tmp56_ = _tmp55_;
				_tmp57_ = name;
				_tmp58_ = strlen (_tmp57_);
				_tmp59_ = _tmp58_;
				_tmp60_ = string_slice (_tmp54_, (glong) _tmp56_, (glong) _tmp59_);
				_tmp61_ = _tmp60_;
				caribou_key_model_set_label (self, _tmp61_);
				_g_free0 (_tmp61_);
			} else {
				guint* _tmp62_;
				gint _tmp62__length1;
				_tmp62_ = self->priv->_keyvals;
				_tmp62__length1 = self->priv->_keyvals_length1;
				if (_tmp62__length1 > 0) {
					gunichar uc = 0U;
					guint* _tmp63_;
					gint _tmp63__length1;
					guint _tmp64_;
					guint32 _tmp65_ = 0U;
					gboolean _tmp66_ = FALSE;
					gunichar _tmp67_;
					gboolean _tmp68_ = FALSE;
					gboolean _tmp70_;
					_tmp63_ = self->priv->_keyvals;
					_tmp63__length1 = self->priv->_keyvals_length1;
					_tmp64_ = _tmp63_[0];
					_tmp65_ = gdk_keyval_to_unicode (_tmp64_);
					uc = (gunichar) _tmp65_;
					_tmp67_ = uc;
					_tmp68_ = g_unichar_isspace (_tmp67_);
					if (!_tmp68_) {
						gunichar _tmp69_;
						_tmp69_ = uc;
						_tmp66_ = _tmp69_ != ((gunichar) 0);
					} else {
						_tmp66_ = FALSE;
					}
					_tmp70_ = _tmp66_;
					if (_tmp70_) {
						gunichar _tmp71_;
						gchar* _tmp72_ = NULL;
						gchar* _tmp73_;
						_tmp71_ = uc;
						_tmp72_ = g_unichar_to_string (_tmp71_);
						_tmp73_ = _tmp72_;
						caribou_key_model_set_label (self, _tmp73_);
						_g_free0 (_tmp73_);
					}
				}
			}
		}
	}
	_tmp74_ = caribou_xadapter_get_default ();
	_g_object_unref0 (self->priv->xadapter);
	self->priv->xadapter = _tmp74_;
	_tmp75_ = gee_array_list_new (CARIBOU_TYPE_KEY_MODEL, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->extended_keys);
	self->priv->extended_keys = _tmp75_;
	return self;
}


CaribouKeyModel* caribou_key_model_new (const gchar* name, const gchar* text) {
	return caribou_key_model_construct (CARIBOU_TYPE_KEY_MODEL, name, text);
}


static void _caribou_key_model_on_subkey_released_caribou_ikeyboard_object_key_released (CaribouIKeyboardObject* _sender, CaribouKeyModel* key, gpointer self) {
	caribou_key_model_on_subkey_released (self, key);
}


void caribou_key_model_add_subkey (CaribouKeyModel* self, CaribouKeyModel* key) {
	CaribouKeyModel* _tmp0_;
	GeeArrayList* _tmp1_;
	CaribouKeyModel* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (key != NULL);
	_tmp0_ = key;
	g_signal_connect_object ((CaribouIKeyboardObject*) _tmp0_, "key-released", (GCallback) _caribou_key_model_on_subkey_released_caribou_ikeyboard_object_key_released, self, 0);
	_tmp1_ = self->priv->extended_keys;
	_tmp2_ = key;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp1_, _tmp2_);
}


static void caribou_key_model_on_subkey_released (CaribouKeyModel* self, CaribouKeyModel* key) {
	CaribouKeyModel* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (key != NULL);
	_tmp0_ = key;
	g_signal_emit_by_name ((CaribouIKeyboardObject*) self, "key-released", _tmp0_);
	caribou_key_model_set_show_subkeys (self, FALSE);
}


static gboolean _caribou_key_model_on_key_held_gsource_func (gpointer self) {
	gboolean result;
	result = caribou_key_model_on_key_held (self);
	return result;
}


void caribou_key_model_press (CaribouKeyModel* self) {
	gboolean _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp5_;
	g_return_if_fail (self != NULL);
	_tmp0_ = caribou_key_model_get_is_modifier (self);
	_tmp1_ = _tmp0_;
	if (_tmp1_) {
		CaribouModifierState _tmp2_;
		_tmp2_ = self->modifier_state;
		if (_tmp2_ == CARIBOU_MODIFIER_STATE_NONE) {
			CaribouXAdapter* _tmp3_;
			GdkModifierType _tmp4_;
			self->modifier_state = CARIBOU_MODIFIER_STATE_LATCHED;
			_tmp3_ = self->priv->xadapter;
			_tmp4_ = self->priv->mod_mask;
			caribou_xadapter_mod_lock (_tmp3_, (guint) _tmp4_);
		} else {
			self->modifier_state = CARIBOU_MODIFIER_STATE_NONE;
		}
	}
	_tmp5_ = self->priv->_repeatable;
	if (_tmp5_) {
		CaribouXAdapter* _tmp6_;
		guint _tmp7_;
		_tmp6_ = self->priv->xadapter;
		_tmp7_ = self->priv->_keyval;
		caribou_xadapter_keyval_press (_tmp6_, _tmp7_);
	} else {
		guint _tmp8_ = 0U;
		_tmp8_ = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 1000, _caribou_key_model_on_key_held_gsource_func, g_object_ref (self), g_object_unref);
		self->priv->hold_tid = _tmp8_;
	}
	g_signal_emit_by_name ((CaribouIKeyboardObject*) self, "key-pressed", self);
}


void caribou_key_model_release (CaribouKeyModel* self) {
	guint _tmp0_;
	gboolean _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp7_;
	guint _tmp15_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->hold_tid;
	if (_tmp0_ != ((guint) 0)) {
		guint _tmp1_;
		_tmp1_ = self->priv->hold_tid;
		g_source_remove (_tmp1_);
	}
	_tmp2_ = caribou_key_model_get_is_modifier (self);
	_tmp3_ = _tmp2_;
	if (_tmp3_) {
		CaribouModifierState _tmp4_;
		_tmp4_ = self->modifier_state;
		if (_tmp4_ == CARIBOU_MODIFIER_STATE_NONE) {
			CaribouXAdapter* _tmp5_;
			GdkModifierType _tmp6_;
			_tmp5_ = self->priv->xadapter;
			_tmp6_ = self->priv->mod_mask;
			caribou_xadapter_mod_unlock (_tmp5_, (guint) _tmp6_);
		} else {
			return;
		}
	}
	_tmp7_ = self->priv->_repeatable;
	if (_tmp7_) {
		CaribouXAdapter* _tmp8_;
		guint _tmp9_;
		_tmp8_ = self->priv->xadapter;
		_tmp9_ = self->priv->_keyval;
		caribou_xadapter_keyval_release (_tmp8_, _tmp9_);
	} else {
		guint* _tmp10_;
		gint _tmp10__length1;
		_tmp10_ = self->priv->_keyvals;
		_tmp10__length1 = self->priv->_keyvals_length1;
		{
			guint* keyval_collection = NULL;
			gint keyval_collection_length1 = 0;
			gint _keyval_collection_size_ = 0;
			gint keyval_it = 0;
			keyval_collection = _tmp10_;
			keyval_collection_length1 = _tmp10__length1;
			for (keyval_it = 0; keyval_it < _tmp10__length1; keyval_it = keyval_it + 1) {
				guint keyval = 0U;
				keyval = keyval_collection[keyval_it];
				{
					CaribouXAdapter* _tmp11_;
					guint _tmp12_;
					CaribouXAdapter* _tmp13_;
					guint _tmp14_;
					_tmp11_ = self->priv->xadapter;
					_tmp12_ = keyval;
					caribou_xadapter_keyval_press (_tmp11_, _tmp12_);
					_tmp13_ = self->priv->xadapter;
					_tmp14_ = keyval;
					caribou_xadapter_keyval_release (_tmp13_, _tmp14_);
				}
			}
		}
	}
	g_signal_emit_by_name ((CaribouIKeyboardObject*) self, "key-released", self);
	_tmp15_ = self->priv->hold_tid;
	if (_tmp15_ != ((guint) 0)) {
		g_signal_emit_by_name ((CaribouIKeyboardObject*) self, "key-clicked", self);
		self->priv->hold_tid = (guint) 0;
	} else {
		g_signal_emit_by_name (self, "key-hold-end");
	}
}


static gboolean caribou_key_model_on_key_held (CaribouKeyModel* self) {
	gboolean result = FALSE;
	GeeArrayList* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_;
	gboolean _tmp5_;
	gboolean _tmp7_;
	g_return_val_if_fail (self != NULL, FALSE);
	self->priv->hold_tid = (guint) 0;
	_tmp0_ = self->priv->extended_keys;
	_tmp1_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ != 0) {
		caribou_key_model_set_show_subkeys (self, TRUE);
	}
	_tmp4_ = caribou_key_model_get_is_modifier (self);
	_tmp5_ = _tmp4_;
	if (_tmp5_) {
		CaribouModifierState _tmp6_;
		_tmp6_ = self->modifier_state;
		_tmp3_ = _tmp6_ == CARIBOU_MODIFIER_STATE_LATCHED;
	} else {
		_tmp3_ = FALSE;
	}
	_tmp7_ = _tmp3_;
	if (_tmp7_) {
		self->modifier_state = CARIBOU_MODIFIER_STATE_LOCKED;
	}
	g_signal_emit_by_name (self, "key-hold");
	result = FALSE;
	return result;
}


CaribouKeyModel** caribou_key_model_get_extended_keys (CaribouKeyModel* self, int* result_length1) {
	CaribouKeyModel** result = NULL;
	GeeArrayList* _tmp0_;
	gint _tmp1_ = 0;
	gpointer* _tmp2_ = NULL;
	CaribouKeyModel** _tmp3_;
	gint _tmp3__length1;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->extended_keys;
	_tmp2_ = gee_collection_to_array ((GeeCollection*) _tmp0_, &_tmp1_);
	_tmp3_ = (CaribouKeyModel**) _tmp2_;
	_tmp3__length1 = (_tmp1_ * sizeof (CaribouKeyModel*)) / sizeof (CaribouKeyModel*);
	if (result_length1) {
		*result_length1 = _tmp3__length1;
	}
	result = _tmp3_;
	return result;
}


static CaribouKeyModel** caribou_key_model_real_get_keys (CaribouIKeyboardObject* base, int* result_length1) {
	CaribouKeyModel * self;
	CaribouKeyModel** result = NULL;
	GeeArrayList* all_keys = NULL;
	GeeArrayList* _tmp0_;
	GeeArrayList* _tmp1_;
	gint _tmp2_ = 0;
	gpointer* _tmp3_ = NULL;
	CaribouKeyModel** _tmp4_;
	gint _tmp4__length1;
	self = (CaribouKeyModel*) base;
	_tmp0_ = gee_array_list_new (CARIBOU_TYPE_KEY_MODEL, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	all_keys = _tmp0_;
	gee_abstract_collection_add ((GeeAbstractCollection*) all_keys, self);
	_tmp1_ = self->priv->extended_keys;
	gee_array_list_add_all (all_keys, (GeeCollection*) _tmp1_);
	_tmp3_ = gee_collection_to_array ((GeeCollection*) all_keys, &_tmp2_);
	_tmp4_ = (CaribouKeyModel**) _tmp3_;
	_tmp4__length1 = (_tmp2_ * sizeof (CaribouKeyModel*)) / sizeof (CaribouKeyModel*);
	if (result_length1) {
		*result_length1 = _tmp4__length1;
	}
	result = _tmp4_;
	_g_object_unref0 (all_keys);
	return result;
}


static CaribouIKeyboardObject** caribou_key_model_real_get_children (CaribouIKeyboardObject* base, int* result_length1) {
	CaribouKeyModel * self;
	CaribouIKeyboardObject** result = NULL;
	GeeArrayList* _tmp0_;
	gint _tmp1_ = 0;
	gpointer* _tmp2_ = NULL;
	CaribouIKeyboardObject** _tmp3_;
	gint _tmp3__length1;
	self = (CaribouKeyModel*) base;
	_tmp0_ = self->priv->extended_keys;
	_tmp2_ = gee_collection_to_array ((GeeCollection*) _tmp0_, &_tmp1_);
	_tmp3_ = (CaribouIKeyboardObject**) _tmp2_;
	_tmp3__length1 = (_tmp1_ * sizeof (CaribouKeyModel*)) / sizeof (CaribouIKeyboardObject*);
	if (result_length1) {
		*result_length1 = _tmp3__length1;
	}
	result = _tmp3_;
	return result;
}


static gboolean __lambda2_ (CaribouKeyModel* self) {
	gboolean result = FALSE;
	caribou_key_model_release (self);
	result = FALSE;
	return result;
}


static gboolean ___lambda2__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda2_ (self);
	return result;
}


void caribou_key_model_activate (CaribouKeyModel* self) {
	g_return_if_fail (self != NULL);
	caribou_key_model_press (self);
	g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 200, ___lambda2__gsource_func, g_object_ref (self), g_object_unref);
}


const gchar* caribou_key_model_get_align (CaribouKeyModel* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_align;
	result = _tmp0_;
	return result;
}


void caribou_key_model_set_align (CaribouKeyModel* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_align);
	self->priv->_align = _tmp1_;
	g_object_notify ((GObject *) self, "align");
}


gdouble caribou_key_model_get_width (CaribouKeyModel* self) {
	gdouble result;
	gdouble _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->priv->_width;
	result = _tmp0_;
	return result;
}


void caribou_key_model_set_width (CaribouKeyModel* self, gdouble value) {
	gdouble _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_width = _tmp0_;
	g_object_notify ((GObject *) self, "width");
}


const gchar* caribou_key_model_get_toggle (CaribouKeyModel* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_toggle;
	result = _tmp0_;
	return result;
}


void caribou_key_model_set_toggle (CaribouKeyModel* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_toggle);
	self->priv->_toggle = _tmp1_;
	g_object_notify ((GObject *) self, "toggle");
}


gboolean caribou_key_model_get_repeatable (CaribouKeyModel* self) {
	gboolean result;
	gboolean _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_repeatable;
	result = _tmp0_;
	return result;
}


void caribou_key_model_set_repeatable (CaribouKeyModel* self, gboolean value) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_repeatable = _tmp0_;
	g_object_notify ((GObject *) self, "repeatable");
}


gboolean caribou_key_model_get_is_modifier (CaribouKeyModel* self) {
	gboolean result;
	GdkModifierType _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->mod_mask;
	result = _tmp0_ != 0;
	return result;
}


void caribou_key_model_set_is_modifier (CaribouKeyModel* self, gboolean value) {
	g_return_if_fail (self != NULL);
	g_object_notify ((GObject *) self, "is-modifier");
}


gboolean caribou_key_model_get_show_subkeys (CaribouKeyModel* self) {
	gboolean result;
	gboolean _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_show_subkeys;
	result = _tmp0_;
	return result;
}


static void caribou_key_model_set_show_subkeys (CaribouKeyModel* self, gboolean value) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_show_subkeys = _tmp0_;
	g_object_notify ((GObject *) self, "show-subkeys");
}


const gchar* caribou_key_model_get_name (CaribouKeyModel* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}


static void caribou_key_model_set_name (CaribouKeyModel* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp1_;
	g_object_notify ((GObject *) self, "name");
}


guint caribou_key_model_get_keyval (CaribouKeyModel* self) {
	guint result;
	guint _tmp0_;
	g_return_val_if_fail (self != NULL, 0U);
	_tmp0_ = self->priv->_keyval;
	result = _tmp0_;
	return result;
}


static void caribou_key_model_set_keyval (CaribouKeyModel* self, guint value) {
	guint _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_keyval = _tmp0_;
	g_object_notify ((GObject *) self, "keyval");
}


const gchar* caribou_key_model_get_text (CaribouKeyModel* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_text;
	result = _tmp0_;
	return result;
}


static void caribou_key_model_set_text (CaribouKeyModel* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_text);
	self->priv->_text = _tmp1_;
	g_object_notify ((GObject *) self, "text");
}


const gchar* caribou_key_model_get_label (CaribouKeyModel* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_label;
	result = _tmp0_;
	return result;
}


static void caribou_key_model_set_label (CaribouKeyModel* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_label);
	self->priv->_label = _tmp1_;
	g_object_notify ((GObject *) self, "label");
}


static gboolean caribou_key_model_real_get_scan_stepping (CaribouIScannableItem* base) {
	gboolean result;
	CaribouKeyModel* self;
	gboolean _tmp0_;
	self = (CaribouKeyModel*) base;
	_tmp0_ = self->priv->_scan_stepping;
	result = _tmp0_;
	return result;
}


static void caribou_key_model_real_set_scan_stepping (CaribouIScannableItem* base, gboolean value) {
	CaribouKeyModel* self;
	gboolean _tmp0_;
	self = (CaribouKeyModel*) base;
	_tmp0_ = value;
	self->priv->_scan_stepping = _tmp0_;
	g_object_notify ((GObject *) self, "scan-stepping");
}


static gboolean caribou_key_model_real_get_scan_selected (CaribouIScannableItem* base) {
	gboolean result;
	CaribouKeyModel* self;
	gboolean _tmp0_;
	self = (CaribouKeyModel*) base;
	_tmp0_ = self->priv->_scan_selected;
	result = _tmp0_;
	return result;
}


static void caribou_key_model_real_set_scan_selected (CaribouIScannableItem* base, gboolean value) {
	CaribouKeyModel* self;
	gboolean _tmp0_;
	gboolean _tmp1_;
	self = (CaribouKeyModel*) base;
	_tmp0_ = value;
	self->priv->_scan_selected = _tmp0_;
	_tmp1_ = self->priv->_scan_selected;
	if (_tmp1_) {
		caribou_key_model_activate (self);
	}
	g_object_notify ((GObject *) self, "scan-selected");
}


static void caribou_key_model_class_init (CaribouKeyModelClass * klass) {
	caribou_key_model_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CaribouKeyModelPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_caribou_key_model_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_caribou_key_model_set_property;
	G_OBJECT_CLASS (klass)->finalize = caribou_key_model_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CARIBOU_KEY_MODEL_ALIGN, g_param_spec_string ("align", "align", "align", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CARIBOU_KEY_MODEL_WIDTH, g_param_spec_double ("width", "width", "width", -G_MAXDOUBLE, G_MAXDOUBLE, 1.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CARIBOU_KEY_MODEL_TOGGLE, g_param_spec_string ("toggle", "toggle", "toggle", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CARIBOU_KEY_MODEL_REPEATABLE, g_param_spec_boolean ("repeatable", "repeatable", "repeatable", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CARIBOU_KEY_MODEL_IS_MODIFIER, g_param_spec_boolean ("is-modifier", "is-modifier", "is-modifier", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CARIBOU_KEY_MODEL_SHOW_SUBKEYS, g_param_spec_boolean ("show-subkeys", "show-subkeys", "show-subkeys", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CARIBOU_KEY_MODEL_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CARIBOU_KEY_MODEL_KEYVAL, g_param_spec_uint ("keyval", "keyval", "keyval", 0, G_MAXUINT, 0U, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CARIBOU_KEY_MODEL_TEXT, g_param_spec_string ("text", "text", "text", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CARIBOU_KEY_MODEL_LABEL, g_param_spec_string ("label", "label", "label", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CARIBOU_KEY_MODEL_SCAN_STEPPING, g_param_spec_boolean ("scan-stepping", "scan-stepping", "scan-stepping", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CARIBOU_KEY_MODEL_SCAN_SELECTED, g_param_spec_boolean ("scan-selected", "scan-selected", "scan-selected", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_signal_new ("key_hold_end", CARIBOU_TYPE_KEY_MODEL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("key_hold", CARIBOU_TYPE_KEY_MODEL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void caribou_key_model_caribou_iscannable_item_interface_init (CaribouIScannableItemIface * iface) {
	caribou_key_model_caribou_iscannable_item_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_scan_stepping = caribou_key_model_real_get_scan_stepping;
	iface->set_scan_stepping = caribou_key_model_real_set_scan_stepping;
	iface->get_scan_selected = caribou_key_model_real_get_scan_selected;
	iface->set_scan_selected = caribou_key_model_real_set_scan_selected;
}


static void caribou_key_model_caribou_ikeyboard_object_interface_init (CaribouIKeyboardObjectIface * iface) {
	caribou_key_model_caribou_ikeyboard_object_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_keys = (CaribouKeyModel** (*)(CaribouIKeyboardObject*, int*)) caribou_key_model_real_get_keys;
	iface->get_children = (CaribouIKeyboardObject** (*)(CaribouIKeyboardObject*, int*)) caribou_key_model_real_get_children;
}


static void caribou_key_model_instance_init (CaribouKeyModel * self) {
	gchar* _tmp0_;
	gchar* _tmp1_;
	guint* _tmp2_ = NULL;
	gchar* _tmp3_;
	self->priv = CARIBOU_KEY_MODEL_GET_PRIVATE (self);
	_tmp0_ = g_strdup ("center");
	self->priv->_align = _tmp0_;
	self->priv->_width = 1.0;
	_tmp1_ = g_strdup ("");
	self->priv->_toggle = _tmp1_;
	self->priv->_repeatable = FALSE;
	self->priv->_show_subkeys = FALSE;
	self->priv->_text = NULL;
	_tmp2_ = g_new0 (guint, 0);
	self->priv->_keyvals = _tmp2_;
	self->priv->_keyvals_length1 = 0;
	self->priv->__keyvals_size_ = self->priv->_keyvals_length1;
	_tmp3_ = g_strdup ("");
	self->priv->_label = _tmp3_;
}


static void caribou_key_model_finalize (GObject* obj) {
	CaribouKeyModel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CARIBOU_TYPE_KEY_MODEL, CaribouKeyModel);
	_g_free0 (self->priv->_align);
	_g_free0 (self->priv->_toggle);
	_g_free0 (self->priv->_name);
	_g_free0 (self->priv->_text);
	self->priv->_keyvals = (g_free (self->priv->_keyvals), NULL);
	_g_free0 (self->priv->_label);
	_g_object_unref0 (self->priv->xadapter);
	_g_object_unref0 (self->priv->extended_keys);
	G_OBJECT_CLASS (caribou_key_model_parent_class)->finalize (obj);
}


/**
     * Object representing a key in a column.
     *
     * This is used for implementing custom keyboard service.
     */
GType caribou_key_model_get_type (void) {
	static volatile gsize caribou_key_model_type_id__volatile = 0;
	if (g_once_init_enter (&caribou_key_model_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CaribouKeyModelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) caribou_key_model_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CaribouKeyModel), 0, (GInstanceInitFunc) caribou_key_model_instance_init, NULL };
		static const GInterfaceInfo caribou_iscannable_item_info = { (GInterfaceInitFunc) caribou_key_model_caribou_iscannable_item_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		static const GInterfaceInfo caribou_ikeyboard_object_info = { (GInterfaceInitFunc) caribou_key_model_caribou_ikeyboard_object_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType caribou_key_model_type_id;
		caribou_key_model_type_id = g_type_register_static (G_TYPE_OBJECT, "CaribouKeyModel", &g_define_type_info, 0);
		g_type_add_interface_static (caribou_key_model_type_id, CARIBOU_TYPE_ISCANNABLE_ITEM, &caribou_iscannable_item_info);
		g_type_add_interface_static (caribou_key_model_type_id, CARIBOU_TYPE_IKEYBOARD_OBJECT, &caribou_ikeyboard_object_info);
		g_once_init_leave (&caribou_key_model_type_id__volatile, caribou_key_model_type_id);
	}
	return caribou_key_model_type_id__volatile;
}


static void _vala_caribou_key_model_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	CaribouKeyModel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CARIBOU_TYPE_KEY_MODEL, CaribouKeyModel);
	switch (property_id) {
		case CARIBOU_KEY_MODEL_ALIGN:
		g_value_set_string (value, caribou_key_model_get_align (self));
		break;
		case CARIBOU_KEY_MODEL_WIDTH:
		g_value_set_double (value, caribou_key_model_get_width (self));
		break;
		case CARIBOU_KEY_MODEL_TOGGLE:
		g_value_set_string (value, caribou_key_model_get_toggle (self));
		break;
		case CARIBOU_KEY_MODEL_REPEATABLE:
		g_value_set_boolean (value, caribou_key_model_get_repeatable (self));
		break;
		case CARIBOU_KEY_MODEL_IS_MODIFIER:
		g_value_set_boolean (value, caribou_key_model_get_is_modifier (self));
		break;
		case CARIBOU_KEY_MODEL_SHOW_SUBKEYS:
		g_value_set_boolean (value, caribou_key_model_get_show_subkeys (self));
		break;
		case CARIBOU_KEY_MODEL_NAME:
		g_value_set_string (value, caribou_key_model_get_name (self));
		break;
		case CARIBOU_KEY_MODEL_KEYVAL:
		g_value_set_uint (value, caribou_key_model_get_keyval (self));
		break;
		case CARIBOU_KEY_MODEL_TEXT:
		g_value_set_string (value, caribou_key_model_get_text (self));
		break;
		case CARIBOU_KEY_MODEL_LABEL:
		g_value_set_string (value, caribou_key_model_get_label (self));
		break;
		case CARIBOU_KEY_MODEL_SCAN_STEPPING:
		g_value_set_boolean (value, caribou_iscannable_item_get_scan_stepping ((CaribouIScannableItem*) self));
		break;
		case CARIBOU_KEY_MODEL_SCAN_SELECTED:
		g_value_set_boolean (value, caribou_iscannable_item_get_scan_selected ((CaribouIScannableItem*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_caribou_key_model_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	CaribouKeyModel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CARIBOU_TYPE_KEY_MODEL, CaribouKeyModel);
	switch (property_id) {
		case CARIBOU_KEY_MODEL_ALIGN:
		caribou_key_model_set_align (self, g_value_get_string (value));
		break;
		case CARIBOU_KEY_MODEL_WIDTH:
		caribou_key_model_set_width (self, g_value_get_double (value));
		break;
		case CARIBOU_KEY_MODEL_TOGGLE:
		caribou_key_model_set_toggle (self, g_value_get_string (value));
		break;
		case CARIBOU_KEY_MODEL_REPEATABLE:
		caribou_key_model_set_repeatable (self, g_value_get_boolean (value));
		break;
		case CARIBOU_KEY_MODEL_IS_MODIFIER:
		caribou_key_model_set_is_modifier (self, g_value_get_boolean (value));
		break;
		case CARIBOU_KEY_MODEL_SHOW_SUBKEYS:
		caribou_key_model_set_show_subkeys (self, g_value_get_boolean (value));
		break;
		case CARIBOU_KEY_MODEL_NAME:
		caribou_key_model_set_name (self, g_value_get_string (value));
		break;
		case CARIBOU_KEY_MODEL_KEYVAL:
		caribou_key_model_set_keyval (self, g_value_get_uint (value));
		break;
		case CARIBOU_KEY_MODEL_TEXT:
		caribou_key_model_set_text (self, g_value_get_string (value));
		break;
		case CARIBOU_KEY_MODEL_LABEL:
		caribou_key_model_set_label (self, g_value_get_string (value));
		break;
		case CARIBOU_KEY_MODEL_SCAN_STEPPING:
		caribou_iscannable_item_set_scan_stepping ((CaribouIScannableItem*) self, g_value_get_boolean (value));
		break;
		case CARIBOU_KEY_MODEL_SCAN_SELECTED:
		caribou_iscannable_item_set_scan_selected ((CaribouIScannableItem*) self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


GType caribou_modifier_state_get_type (void) {
	static volatile gsize caribou_modifier_state_type_id__volatile = 0;
	if (g_once_init_enter (&caribou_modifier_state_type_id__volatile)) {
		static const GEnumValue values[] = {{CARIBOU_MODIFIER_STATE_NONE, "CARIBOU_MODIFIER_STATE_NONE", "none"}, {CARIBOU_MODIFIER_STATE_LATCHED, "CARIBOU_MODIFIER_STATE_LATCHED", "latched"}, {CARIBOU_MODIFIER_STATE_LOCKED, "CARIBOU_MODIFIER_STATE_LOCKED", "locked"}, {0, NULL, NULL}};
		GType caribou_modifier_state_type_id;
		caribou_modifier_state_type_id = g_enum_register_static ("CaribouModifierState", values);
		g_once_init_leave (&caribou_modifier_state_type_id__volatile, caribou_modifier_state_type_id);
	}
	return caribou_modifier_state_type_id__volatile;
}


void caribou_modifier_map_entry_copy (const CaribouModifierMapEntry* self, CaribouModifierMapEntry* dest) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	GdkModifierType _tmp2_;
	_tmp0_ = (*self).name;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).name);
	(*dest).name = _tmp1_;
	_tmp2_ = (*self).mask;
	(*dest).mask = _tmp2_;
}


void caribou_modifier_map_entry_destroy (CaribouModifierMapEntry* self) {
	_g_free0 ((*self).name);
}


CaribouModifierMapEntry* caribou_modifier_map_entry_dup (const CaribouModifierMapEntry* self) {
	CaribouModifierMapEntry* dup;
	dup = g_new0 (CaribouModifierMapEntry, 1);
	caribou_modifier_map_entry_copy (self, dup);
	return dup;
}


void caribou_modifier_map_entry_free (CaribouModifierMapEntry* self) {
	caribou_modifier_map_entry_destroy (self);
	g_free (self);
}


GType caribou_modifier_map_entry_get_type (void) {
	static volatile gsize caribou_modifier_map_entry_type_id__volatile = 0;
	if (g_once_init_enter (&caribou_modifier_map_entry_type_id__volatile)) {
		GType caribou_modifier_map_entry_type_id;
		caribou_modifier_map_entry_type_id = g_boxed_type_register_static ("CaribouModifierMapEntry", (GBoxedCopyFunc) caribou_modifier_map_entry_dup, (GBoxedFreeFunc) caribou_modifier_map_entry_free);
		g_once_init_leave (&caribou_modifier_map_entry_type_id__volatile, caribou_modifier_map_entry_type_id);
	}
	return caribou_modifier_map_entry_type_id__volatile;
}


void caribou_label_map_entry_copy (const CaribouLabelMapEntry* self, CaribouLabelMapEntry* dest) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	_tmp0_ = (*self).name;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).name);
	(*dest).name = _tmp1_;
	_tmp2_ = (*self).label;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 ((*dest).label);
	(*dest).label = _tmp3_;
}


void caribou_label_map_entry_destroy (CaribouLabelMapEntry* self) {
	_g_free0 ((*self).name);
	_g_free0 ((*self).label);
}


CaribouLabelMapEntry* caribou_label_map_entry_dup (const CaribouLabelMapEntry* self) {
	CaribouLabelMapEntry* dup;
	dup = g_new0 (CaribouLabelMapEntry, 1);
	caribou_label_map_entry_copy (self, dup);
	return dup;
}


void caribou_label_map_entry_free (CaribouLabelMapEntry* self) {
	caribou_label_map_entry_destroy (self);
	g_free (self);
}


GType caribou_label_map_entry_get_type (void) {
	static volatile gsize caribou_label_map_entry_type_id__volatile = 0;
	if (g_once_init_enter (&caribou_label_map_entry_type_id__volatile)) {
		GType caribou_label_map_entry_type_id;
		caribou_label_map_entry_type_id = g_boxed_type_register_static ("CaribouLabelMapEntry", (GBoxedCopyFunc) caribou_label_map_entry_dup, (GBoxedFreeFunc) caribou_label_map_entry_free);
		g_once_init_leave (&caribou_label_map_entry_type_id__volatile, caribou_label_map_entry_type_id);
	}
	return caribou_label_map_entry_type_id__volatile;
}



